# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    app.openai.api_key: '%env(OPENAI_API_KEY)%'
    app.openai.model: '%env(string:OPENAI_MODEL)%'
    app.upload_dir: '%kernel.project_dir%/var/uploads'
    plant_uploads_directory: '%kernel.project_dir%/public/uploads/plants'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\PlantRecognitionService:
        arguments:
            $apiKey: '%app.openai.api_key%'
            $model: '%app.openai.model%'
